'\" t
.\"     Title: bpm
.\"    Author: Qball Cow qball@gmpclient.org
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 01/04/2014
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "BPM" "1" "01/04/2014" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
BPM \- Small command\-line tool to store data from Beurer BM58 Blood Pressure Monitor
.SH "SYNOPSYS"
.sp
bpm [\fIcommand\fR]
.SH "DESCRIPTION"
.sp
This manual page explains the \fBBPM\fR program\&. The \fBBPM\fR program retrieves, stores and outputs blood pressure measurements from a Beurer BM56 Blood Pressure Monitor\&. (Any device based on Andon Blood Pressure Meter KD001 should work)\&.
.sp
Be default these devices can only store up to 60 data points\&. This tool is written to extend that and allow the data to be used by 3rd party programs like gnuplot\&. It outputs the stored points in different formats like txt and csv, and if requested, filter multiple measurements taken at the same time\&.
.SH "COMMANDS"
.sp
Multiple commands can be specified in one go, they are handled in order\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBimport\fR
Import data from the Blood Pressure Monitor into the local database\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBlist\fR
List all logged data points\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBcsv\fR
Output logged data points in Comma Separated Value format\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBtxt\fR
Output logged data points in simple text format\&. This format can be used directly in gnuplot\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBavg\fR
Display average systolic and diastolic pressure\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBfilter\fR
Measurements taken within 10 minutes of each other are averaged\&.
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
bpm import filter csv
.fi
.if n \{\
.RE
.\}
.sp
Imports the latest samples from the Blood Pressure Monitor and outputs a filtered, comma separated value list\&.
.SH "ENVIRONMENT VARIABLES"
.sp
BPM obeys the following environment variables:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBBPM_PATH\fR
The full path to the database file\&.
.RE
.sp
\fIDefault:\fR
.sp
.if n \{\
.RS 4
.\}
.nf
$(HOME)/\&.bpm\&.sqlite3
.fi
.if n \{\
.RE
.\}
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBBPM_DEVICE\fR
The device node pointing to the serial device of the Bloop Pressure Monitor
.RE
.sp
\fIDefault:\fR
.sp
.if n \{\
.RS 4
.\}
.nf
/dev/ttyUSB0
.fi
.if n \{\
.RE
.\}
.SH "SUPPORTED DEVICES"
.sp
The following device(s) are known to work:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Beurer medical BM58
.RE
.SH "BUGS"
.sp
Please report bugs on the GITHUB issues page: https://github\&.com/DaveDavenport/bpm
.SH "LICENSE"
.sp
This program is licensed under GPL 2\&.0\&.
.SH "NOTES"
.sp
The program is available as\-is\&. It is not a medical\-grade program and should not be used for this purpose\&.
.SH "SEE ALSO"
.sp
gnuplot(1)
.SH "AUTHOR"
.PP
\fBQball Cow qball@gmpclient\&.org\fR
.RS 4
Author.
.RE
