BPM(1)
======
:Author: Qball Cow qball@gmpclient.org
:doctype: manpage
:home: /main.html
:toc:


Name
----
BPM - Small command-line tool to store data from Beurer BM58 Blood Pressure Monitor

Synopsys
--------
bpm ['command']

DESCRIPTION
-----------

This manual page explains the *BPM* program. The *BPM* program retrieves, stores and outputs 
blood pressure measurements from a Beurer BM56 Blood Pressure Monitor.
(Any device based on  Andon Blood Pressure Meter KD001 should work).

By default these devices can only store up to 60 data points.
This tool is written to extend that and allow the data to be used by 3rd party programs like gnuplot.
It outputs the stored points in different formats like txt and csv, and if requested, filter 
multiple measurements taken at the same time. 


COMMANDS
--------
Multiple commands can be specified in one go, they are handled in order.

 * *import*
Import data from the Blood Pressure Monitor into the local database.

 * *list*
List all logged data points.

 * *csv*
Output logged data points in Comma Separated Value format.

 * *txt*
Output logged data points in simple text format.
This format can be used directly in gnuplot.

 * *avg*
Display average systolic and diastolic pressure.

 * *filter*
Measurements taken within 10 minutes of each other are averaged.

 * *filter <filter>*
Measurements taken within <mins> minutes of each other are averaged.

 * *plot <filter>*
Call gnuplot to plot the blood pressure.

 * *status*
Print status based on last measurements.

 * *add* <systolic> <diastolic> <bpm>
Add a manual entry to the list. (dated now)

* *help*
This help message.


FILTER SYNTAX
-------------

If left empty the default is used (10m filter). It allows two formats

 * <minutes>

 * <days>d

So to filter samples per 1 day, type 'filter 1d'.

EXAMPLES
--------

   bpm import filter csv

Imports the latest samples from the Blood Pressure Monitor and outputs a filtered, comma separated 
value list.

ENVIRONMENT VARIABLES
---------------------

BPM obeys the following environment variables:

*  *BPM_PATH*
The full path to the database file.

'Default:'

 $(HOME)/.bpm.sqlite3

* *BPM_DEVICE*
The device node pointing to the serial device of the Bloop Pressure Monitor

'Default:'

 /dev/ttyUSB0


SUPPORTED DEVICES
-----------------

The following device(s) are known to work:

 * Beurer medical BM58

EXAMPLES
--------

  bpm filter 1d list

List for each day the measured average.

BUGS
----

Please report bugs on the GITHUB issues page: https://github.com/DaveDavenport/bpm

LICENSE
-------

This program is licensed under GPL 2.0.

NOTES
-----

The program is available as-is. It is not a medical-grade program and should not be used for this 
purpose.

SEE ALSO
--------
gnuplot(1)
